heat_template_version: 2014-10-16

description: |
  Deploy specified package on a server with Ansible

parameters:

  servers:
    type: json

  package:
    type: string

resources:

  configure_package:
    type: OS::Heat::SoftwareConfig
    properties:
      group: ansible
      config:
        str_replace:
          template: |
            ---
            - name: Install and run %package%
              connection: local
              hosts: localhost
              tasks:
               - name: Install %package%
                 apt: pkg=%package% state=installed update_cache=true
                 notify:
                  - Start %package%
              handlers:
               - name: Start %package%
                 service: name=%package% state=started
          params:
            "%package%": { get_param: package }

  deploy_package:
    type: OS::Heat::SoftwareDeploymentGroup
    properties:
      signal_transport: TEMP_URL_SIGNAL
      config:
        get_resource: configure_package
      servers:
        get_param: servers

outputs:
  stdout:
    description: Ansible Output
    value:
      get_attr: [ deploy_package, deploy_stdout ]
  stderr:
    description: Ansible Error Output
    value:
      get_attr: [ deploy_package, deploy_stderr ]
  status_code:
    description: Exit Code
    value:
      get_attr: [ deploy_package, deploy_status_code ]
