heat_template_version: 2014-10-16

description: |
  This template is for testing child templates with

parameters:

  image:  # it must have the SoftwareConfig agent baked-in
    type: string

resources:

  server_pw:
    type: OS::Heat::RandomString

  server1:
    type: OS::Nova::Server
    properties:
      image: { get_param: image }
      admin_pass: { get_attr: [ server_pw, value ] }
      flavor: 2 GB Performance
      software_config_transport: POLL_TEMP_URL
      config_drive: true
      user_data_format: SOFTWARE_CONFIG

  config1:
    type: nginx.yaml
    properties:
      servers:
        'server1': { get_attr: [ server1, show, id ] }

  server2:
    type: OS::Nova::Server
    properties:
      image: { get_param: image }
      admin_pass: { get_attr: [ server_pw, value ] }
      flavor: 2 GB Performance
      software_config_transport: POLL_TEMP_URL
      config_drive: true
      user_data_format: SOFTWARE_CONFIG

  config2:
    type: generic.yaml
    properties:
      servers:
        'server2': { get_attr: [ server2, show, id ] }
      package: nginx

outputs:
  server1_ip:
    description: Server 1 IP Address
    value:
      get_attr: [ server1, accessIPv4 ]
  server1_ip:
    description: Server 2 IP Address
    value:
      get_attr: [ server2, accessIPv4 ]
  server_password:
    description: Server Password
    value:
      get_attr: [ server_pw, value ]
